image: java:8

stages:
  - build

before_script:
  - chmod +x gradlew

cache:
  paths:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

build:
  stage: build
  script:
    - ./gradlew assemble
  allow_failure: false
  artifacts:
    paths:
      - ./build/libs/
